# Load ~/.extra, ~/.bash_prompt, ~/.exports, ~/.aliases and ~/.functions
# ~/.extra can be used for settings you don’t want to commit
for file in ~/.{extra,bash_prompt,exports,aliases,functions}; do
	[ -r "$file" ] && source "$file"
done
unset file

# set vim as command line editor
set -o vi
bind -m vi-command ".":insert-last-argument

# gives time now
function now {
  date +%m/%d-%H:%M
}

# init z   https://github.com/rupa/z
# . ~/code/z/z.sh

# use rvm

# Case-insensitive globbing (used in pathname expansion)
shopt -s nocaseglob

# Prefer US English and use UTF-8
export LC_ALL="en_US.UTF-8"
export LANG="en_US"

# Add tab completion for SSH hostnames based on ~/.ssh/config, ignoring wildcards
[ -e "$HOME/.ssh/config" ] && complete -o "default" -o "nospace" -W "$(grep "^Host" ~/.ssh/config | grep -v "[?*]" | cut -d " " -f2)" scp sftp ssh

# Add tab completion for `defaults read|write NSGlobalDomain`
# You could just use `-g` instead, but I like being explicit
complete -W "NSGlobalDomain" defaults


# Bash Git Completion
source ~/.git-completion.bash

__git_complete gb _git_branch
__git_complete gco _git_checkout
__git_complete gpl _git_push

# git ignore all things in ~/.gitignore_global file
git config --global --replace-all core.excludesfile ~/.gitignore_global

export PATH=$PATH:~/bin

export PATH=/usr/local/bin:$PATH

export PATH=$PATH:/Applications/Postgres.app/Contents/Versions/9.6/bin

export PATH=~/.rbenv/shims:$PATH

# source nvm
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && . "$NVM_DIR/nvm.sh" # This loads nvm

#rbenv init
export PATH="$HOME/.rbenv/bin:$PATH"
eval "$(rbenv init -)"

#pyenv init
eval "$(pyenv init -)"
#pin global python version to 3.6.2
export PYENV_VERSION=3.6.2

# Setting PATH for Python 3.6
# The original version is saved in .bash_profile.pysave
PATH="/Library/Frameworks/Python.framework/Versions/3.6/bin:${PATH}"
export PATH

# added by Anaconda3 5.0.1 installer
export PATH="/Users/joshuabook/anaconda3/bin:$PATH"
